title: code4food
email: vbochenin@gmail.com
description: >-
  Java developer diary about tasks  I'm doing to get some food.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vbochenin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository:  vbochenin/code.vbochenin.github.io 
github: vbochenin

header_image: assets/profile.png

google_analytics: 1
comments: true
disqus:

author: Vladislav Bochenin
author_bio: >- 
  Writing code more than 16 years and raising a son last 7 years. <br/>
  So I more experienced in coding than raising.

author_pic: assets/profile-sm.png

paginate: 5
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author:
      avatar: assets/profile-sm.png
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
      avatar: assets/profile-sm.png
      
# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  notes:
    output: true
    permalink: /notes/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
